"""Write LaTeX tables and number macros that main.tex reads with \\input."""
import pandas as pd

import config

CITIES = list(config.CITIES)
PH = r"\textcolor{red}{??}"


def fp(p: float) -> str:
    return r"$<$0.001" if p < 0.001 else f"{p:.3f}"


def fr(r: float) -> str:
    return f"${r:+.2f}$".replace("+", r"\phantom{-}") if r >= 0 else f"${r:.2f}$"


def tests_table(mw: dict, corr: dict, placeholder=False) -> str:
    has_blh = (not placeholder) and any(r["var"] == "BLH" for rows in corr.values() for r in rows)
    head = (r"\textbf{City} & \multicolumn{2}{c}{\textbf{Median (\ugm{})}} & \multicolumn{2}{c}{\textbf{Mann--Whitney}}"
            r" & \multicolumn{3}{c}{\textbf{Spearman with temperature}}" + (r" & $\rho_{BLH\mid m}$" if has_blh else "") + r" \\" "\n"
            r" & Heating & Non-heat. & $r_{rb}$ & $p$ & $\rho_T$ & $\rho_{T\mid m}$ & $\rho_{T}^{\,\mathcal{H}}$" + (" & " if has_blh else "") + r" \\")
    ncol = 9 if has_blh else 8
    lines = [r"\begin{tabular}{@{}l" + "c" * (ncol - 1) + "@{}}", r"\toprule", head, r"\midrule"]
    for c in CITIES:
        if placeholder:
            lines.append(f"{c} & " + " & ".join([PH] * (ncol - 1)) + r" \\")
            continue
        m = mw[c]
        t = next(r for r in corr[c] if r["var"] == "T")
        cells = [f"{m['median_heat']:.1f}", f"{m['median_non']:.1f}", f"{m['r_rb']:.2f}", fp(m["p_mw"]),
                 fr(t["rho"]) + ("" if t["p"] < 0.05 else r"$^{\mathrm{ns}}$"),
                 fr(t["rho_partial"]) + ("" if t["p_partial"] < 0.05 else r"$^{\mathrm{ns}}$"),
                 fr(t["rho_heating"]) + ("" if t["p_heating"] < 0.05 else r"$^{\mathrm{ns}}$")]
        if has_blh:
            b = next((r for r in corr[c] if r["var"] == "BLH"), None)
            cells.append(fr(b["rho_partial"]) + ("" if b["p_partial"] < 0.05 else r"$^{\mathrm{ns}}$") if b else "--")
        lines.append(f"{c} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def forecast_table(res: pd.DataFrame | None, placeholder=False) -> str:
    lines = [r"\begin{tabular}{@{}l" + "c" * len(CITIES) + "@{}}", r"\toprule",
             r"\textbf{Trained on} $\downarrow$ / \textbf{tested on} $\rightarrow$ & " + " & ".join(rf"\textbf{{{c}}}" for c in CITIES) + r" \\",
             r"\midrule"]
    for tr in CITIES + ["persistence"]:
        label = "Persistence baseline" if tr == "persistence" else tr
        if tr == "persistence":
            lines.append(r"\midrule")
        cells = []
        for te in CITIES:
            if placeholder:
                cells.append(PH)
                continue
            r = res[(res.train == tr) & (res.test == te)].iloc[0]
            txt = f"{r.rmse:.1f}"
            if tr != "persistence":
                txt += " (" + f"{r.skill * 100:+.0f}".replace("-", "$-$") + r"\%)"
            cells.append(rf"\textbf{{{txt}}}" if tr == te else txt)
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def numbers(values: dict | None) -> str:
    keys = ["FcCutoff", "FcHorizon", "PenaltyMean", "PenaltyMax", "PenaltyMaxPair",
            "SelfRtwoAlmaty", "SelfRtwoBishkek", "SelfRtwoTashkent",
            "TopFeatAlmaty", "TopFeatBishkek", "TopFeatTashkent",
            "CompAlmaty", "CompBishkek", "CompTashkent", "TzNote"]
    out = ["% Auto-generated by run_all.py. Do not edit by hand."]
    for k in keys:
        v = PH if values is None else values.get(k, PH)
        out.append(rf"\providecommand{{\{k}}}{{}}\renewcommand{{\{k}}}{{{v}}}")
    return "\n".join(out) + "\n"


def write(name: str, text: str):
    (config.RESULTS_DIR / name).write_text(text)
